main: com.cavetale.hideandseek.HideAndSeekPlugin

name: HideAndSeek
version: 0.1
description: HideAndSeek Plugin
api-version: 1.18

author: StarTux
website: https://github.com/StarTux/HideAndSeek

depend: [Core, PlayerCache, Sidebar, Title, Fam, Mytems]
softdepend: []

commands:

  hideandseek:
    aliases: [hideandseekadmin, hsa]
    description: HideAndSeek Command
    permission: hideandseek.admin
    usage: |-
      /hideandseek setworld - Select current world (player only)
      /hideandseek start - Start a game
      /hideandseek stop - Stop the game
      /hideandseek save - Save runtime
      /hideandseek load - (Re)load runtime
      /hideandseek fair - List player fairness
      /hideandseek score reset - Score reset
      /hideandseek score add <player> <amount> - Manipulate scores

permissions:

  hideandseek.hideandseek:
    description: Use /hideandseek
    default: op

  hideandseek.admin:
    description: Use /hideandseek
    default: op
